/*
 * Copyright 2016 Hani Al Momani
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.kevalpatel2106.emoji_keyboard.internal.emoticons.emoji;

import com.kevalpatel2106.emoji_keyboard.internal.emoticons.Emoticon;

/**
 * @author Hani Al Momani (hani.momanii@gmail.com)
 */
public class People {
    public static final Emoticon[] DATA = new Emoticon[]{
            Emoticon.fromCodePoint(0x1f600),
            Emoticon.fromCodePoint(0x1f62c),
            Emoticon.fromCodePoint(0x1f601),
            Emoticon.fromCodePoint(0x1f602),
            Emoticon.fromCodePoint(0x1f603),
            Emoticon.fromCodePoint(0x1f604),
            Emoticon.fromCodePoint(0x1f605),
            Emoticon.fromCodePoint(0x1f606),
            Emoticon.fromCodePoint(0x1f607),
            Emoticon.fromCodePoint(0x1f609),
            Emoticon.fromCodePoint(0x1f60a),
            Emoticon.fromCodePoint(0x1f642),
            Emoticon.fromCodePoint(0x1f643),
            Emoticon.fromChar((char) 0x263a),
            Emoticon.fromCodePoint(0x1f60b),
            Emoticon.fromCodePoint(0x1f60c),
            Emoticon.fromCodePoint(0x1f60d),
            Emoticon.fromCodePoint(0x1f618),
            Emoticon.fromCodePoint(0x1f617),
            Emoticon.fromCodePoint(0x1f619),
            Emoticon.fromCodePoint(0x1f61a),
            Emoticon.fromCodePoint(0x1f61c),
            Emoticon.fromCodePoint(0x1f61d),
            Emoticon.fromCodePoint(0x1f61b),
            Emoticon.fromCodePoint(0x1f911),
            Emoticon.fromCodePoint(0x1f913),
            Emoticon.fromCodePoint(0x1f60e),
            Emoticon.fromCodePoint(0x1f917),
            Emoticon.fromCodePoint(0x1f60f),
            Emoticon.fromCodePoint(0x1f636),
            Emoticon.fromCodePoint(0x1f610),
            Emoticon.fromCodePoint(0x1f611),
            Emoticon.fromCodePoint(0x1f612),
            Emoticon.fromCodePoint(0x1f644),
            Emoticon.fromCodePoint(0x1f914),
            Emoticon.fromCodePoint(0x1f633),
            Emoticon.fromCodePoint(0x1f61e),
            Emoticon.fromCodePoint(0x1f61f),
            Emoticon.fromCodePoint(0x1f620),
            Emoticon.fromCodePoint(0x1f621),
            Emoticon.fromCodePoint(0x1f614),
            Emoticon.fromCodePoint(0x1f615),
            Emoticon.fromCodePoint(0x1f641),
            Emoticon.fromChar((char) 0x2639),
            Emoticon.fromCodePoint(0x1f623),
            Emoticon.fromCodePoint(0x1f616),
            Emoticon.fromCodePoint(0x1f62b),
            Emoticon.fromCodePoint(0x1f629),
            Emoticon.fromCodePoint(0x1f624),
            Emoticon.fromCodePoint(0x1f62e),
            Emoticon.fromCodePoint(0x1f631),
            Emoticon.fromCodePoint(0x1f628),
            Emoticon.fromCodePoint(0x1f630),
            Emoticon.fromCodePoint(0x1f62f),
            Emoticon.fromCodePoint(0x1f626),
            Emoticon.fromCodePoint(0x1f627),
            Emoticon.fromCodePoint(0x1f622),
            Emoticon.fromCodePoint(0x1f625),
            Emoticon.fromCodePoint(0x1f62a),
            Emoticon.fromCodePoint(0x1f613),
            Emoticon.fromCodePoint(0x1f62d),
            Emoticon.fromCodePoint(0x1f635),
            Emoticon.fromCodePoint(0x1f632),
            Emoticon.fromCodePoint(0x1f910),
            Emoticon.fromCodePoint(0x1f637),
            Emoticon.fromCodePoint(0x1f912),
            Emoticon.fromCodePoint(0x1f915),
            Emoticon.fromCodePoint(0x1f634),
            Emoticon.fromCodePoint(0x1f4a4),
            Emoticon.fromCodePoint(0x1f4a9),
            Emoticon.fromCodePoint(0x1f608),
            Emoticon.fromCodePoint(0x1f47f),
            Emoticon.fromCodePoint(0x1f479),
            Emoticon.fromCodePoint(0x1f47a),
            Emoticon.fromCodePoint(0x1f480),
            Emoticon.fromCodePoint(0x1f47b),
            Emoticon.fromCodePoint(0x1f47d),
            Emoticon.fromCodePoint(0x1f916),
            Emoticon.fromCodePoint(0x1f63a),
            Emoticon.fromCodePoint(0x1f638),
            Emoticon.fromCodePoint(0x1f639),
            Emoticon.fromCodePoint(0x1f63b),
            Emoticon.fromCodePoint(0x1f63c),
            Emoticon.fromCodePoint(0x1f63d),
            Emoticon.fromCodePoint(0x1f640),
            Emoticon.fromCodePoint(0x1f63f),
            Emoticon.fromCodePoint(0x1f63e),
            Emoticon.fromCodePoint(0x1f64c),
            Emoticon.fromCodePoint(0x1f44f),
            Emoticon.fromCodePoint(0x1f44b),
            Emoticon.fromCodePoint(0x1f44d),
            Emoticon.fromCodePoint(0x1f44e),
            Emoticon.fromCodePoint(0x1f44a),
            Emoticon.fromChar((char) 0x270a),
            Emoticon.fromChar((char) 0x270c),
            Emoticon.fromCodePoint(0x1f44c),
            Emoticon.fromChar((char) 0x270b),
            Emoticon.fromCodePoint(0x1f450),
            Emoticon.fromCodePoint(0x1f4aa),
            Emoticon.fromCodePoint(0x1f64f),
            Emoticon.fromChar((char) 0x261d),
            Emoticon.fromCodePoint(0x1f446),
            Emoticon.fromCodePoint(0x1f447),
            Emoticon.fromCodePoint(0x1f448),
            Emoticon.fromCodePoint(0x1f449),
            Emoticon.fromCodePoint(0x1f595),
            Emoticon.fromCodePoint(0x1f590),
            Emoticon.fromCodePoint(0x1f918),
            Emoticon.fromChar((char) 0x270d),
            Emoticon.fromCodePoint(0x1f485),
            Emoticon.fromCodePoint(0x1f444),
            Emoticon.fromCodePoint(0x1f445),
            Emoticon.fromCodePoint(0x1f442),
            Emoticon.fromCodePoint(0x1f443),
            Emoticon.fromCodePoint(0x1f441),
            Emoticon.fromCodePoint(0x1f440),
            Emoticon.fromCodePoint(0x1f464),
            Emoticon.fromCodePoint(0x1f465),
            Emoticon.fromCodePoint(0x1f5e3),
            Emoticon.fromCodePoint(0x1f476),
            Emoticon.fromCodePoint(0x1f466),
            Emoticon.fromCodePoint(0x1f467),
            Emoticon.fromCodePoint(0x1f468),
            Emoticon.fromCodePoint(0x1f469),
            Emoticon.fromCodePoint(0x1f471),
            Emoticon.fromCodePoint(0x1f474),
            Emoticon.fromCodePoint(0x1f475),
            Emoticon.fromCodePoint(0x1f472),
            Emoticon.fromCodePoint(0x1f473),
            Emoticon.fromCodePoint(0x1f46e),
            Emoticon.fromCodePoint(0x1f477),
            Emoticon.fromCodePoint(0x1f482),
            Emoticon.fromCodePoint(0x1f575),
            Emoticon.fromCodePoint(0x1f385),
            Emoticon.fromCodePoint(0x1f47c),
            Emoticon.fromCodePoint(0x1f478),
            Emoticon.fromCodePoint(0x1f470),
            Emoticon.fromCodePoint(0x1f6b6),
            Emoticon.fromCodePoint(0x1f3c3),
            Emoticon.fromCodePoint(0x1f483),
            Emoticon.fromCodePoint(0x1f46f),
            Emoticon.fromCodePoint(0x1f525),
            Emoticon.fromChar((char) 0x2728),
            Emoticon.fromCodePoint(0x1f31f),
            Emoticon.fromCodePoint(0x1f4ab),
            Emoticon.fromCodePoint(0x1f4a2),
            Emoticon.fromCodePoint(0x1f46b),
            Emoticon.fromCodePoint(0x1f46c),
            Emoticon.fromCodePoint(0x1f46d),
            Emoticon.fromCodePoint(0x1f647),
            Emoticon.fromCodePoint(0x1f481),
            Emoticon.fromCodePoint(0x1f645),
            Emoticon.fromCodePoint(0x1f646),
            Emoticon.fromCodePoint(0x1f64b),
            Emoticon.fromCodePoint(0x1f64e),
            Emoticon.fromCodePoint(0x1f64d),
            Emoticon.fromCodePoint(0x1f487),
            Emoticon.fromCodePoint(0x1f486),
            Emoticon.fromCodePoint(0x1f491),
            Emoticon.fromCodePoint(0x1f48f),
            Emoticon.fromCodePoint(0x1f46a),
            Emoticon.fromCodePoint(0x1f45a),
            Emoticon.fromCodePoint(0x1f455),
            Emoticon.fromCodePoint(0x1f456),
            Emoticon.fromCodePoint(0x1f454),
            Emoticon.fromCodePoint(0x1f457),
            Emoticon.fromCodePoint(0x1f459),
            Emoticon.fromCodePoint(0x1f458),
            Emoticon.fromCodePoint(0x1f484),
            Emoticon.fromCodePoint(0x1f48b),
            Emoticon.fromCodePoint(0x1f463),
            Emoticon.fromCodePoint(0x1f460),
            Emoticon.fromCodePoint(0x1f461),
            Emoticon.fromCodePoint(0x1f462),
            Emoticon.fromCodePoint(0x1f45e),
            Emoticon.fromCodePoint(0x1f45f),
            Emoticon.fromCodePoint(0x1f452),
            Emoticon.fromCodePoint(0x1f3a9),
            Emoticon.fromCodePoint(0x1f393),
            Emoticon.fromCodePoint(0x1f451),
            Emoticon.fromChar((char) 0x26d1),
            Emoticon.fromChar((char) 0xe43a),
            Emoticon.fromCodePoint(0x1f45d),
            Emoticon.fromCodePoint(0x1f45b),
            Emoticon.fromCodePoint(0x1f45c),
            Emoticon.fromCodePoint(0x1f4bc),
            Emoticon.fromCodePoint(0x1f453),
            Emoticon.fromCodePoint(0x1f576),
            Emoticon.fromCodePoint(0x1f48d),
            Emoticon.fromCodePoint(0x1f302),
    };
}
