/*
 * Copyright 2016 Hani Al Momani
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.kevalpatel2106.emoticongifkeyboard.internal.emoticons.emoji;

import com.kevalpatel2106.emoticongifkeyboard.internal.emoticons.Emoticon;

/**
 * @author Hani Al Momani (hani.momanii@gmail.com)
 */
public class Nature {
    public static final Emoticon[] DATA = new Emoticon[]{
            Emoticon.fromCodePoint(0x1f436),
            Emoticon.fromCodePoint(0x1f431),
            Emoticon.fromCodePoint(0x1f42d),
            Emoticon.fromCodePoint(0x1f439),
            Emoticon.fromCodePoint(0x1f430),
            Emoticon.fromCodePoint(0x1f43b),
            Emoticon.fromCodePoint(0x1f43c),
            Emoticon.fromCodePoint(0x1f428),
            Emoticon.fromCodePoint(0x1f42f),
            Emoticon.fromCodePoint(0x1f981),
            Emoticon.fromCodePoint(0x1f42e),
            Emoticon.fromCodePoint(0x1f437),
            Emoticon.fromCodePoint(0x1f43d),
            Emoticon.fromCodePoint(0x1f438),
            Emoticon.fromCodePoint(0x1f419),
            Emoticon.fromCodePoint(0x1f435),
            Emoticon.fromCodePoint(0x1f648),
            Emoticon.fromCodePoint(0x1f649),
            Emoticon.fromCodePoint(0x1f64a),
            Emoticon.fromCodePoint(0x1f412),
            Emoticon.fromCodePoint(0x1f414),
            Emoticon.fromCodePoint(0x1f427),
            Emoticon.fromCodePoint(0x1f426),
            Emoticon.fromCodePoint(0x1f424),
            Emoticon.fromCodePoint(0x1f423),
            Emoticon.fromCodePoint(0x1f425),
            Emoticon.fromCodePoint(0x1f43a),
            Emoticon.fromCodePoint(0x1f417),
            Emoticon.fromCodePoint(0x1f434),
            Emoticon.fromCodePoint(0x1f984),
            Emoticon.fromCodePoint(0x1f41d),
            Emoticon.fromCodePoint(0x1f41b),
            Emoticon.fromCodePoint(0x1f40c),
            Emoticon.fromCodePoint(0x1f41e),
            Emoticon.fromCodePoint(0x1f41c),
            Emoticon.fromCodePoint(0x1f577),
            Emoticon.fromCodePoint(0x1f982),
            Emoticon.fromCodePoint(0x1f980),
            Emoticon.fromCodePoint(0x1f40d),
            Emoticon.fromCodePoint(0x1f422),
            Emoticon.fromCodePoint(0x1f420),
            Emoticon.fromCodePoint(0x1f41f),
            Emoticon.fromCodePoint(0x1f421),
            Emoticon.fromCodePoint(0x1f42c),
            Emoticon.fromCodePoint(0x1f433),
            Emoticon.fromCodePoint(0x1f40b),
            Emoticon.fromCodePoint(0x1f40a),
            Emoticon.fromCodePoint(0x1f406),
            Emoticon.fromCodePoint(0x1f405),
            Emoticon.fromCodePoint(0x1f403),
            Emoticon.fromCodePoint(0x1f402),
            Emoticon.fromCodePoint(0x1f404),
            Emoticon.fromCodePoint(0x1f42a),
            Emoticon.fromCodePoint(0x1f42b),
            Emoticon.fromCodePoint(0x1f418),
            Emoticon.fromCodePoint(0x1f410),
            Emoticon.fromCodePoint(0x1f40f),
            Emoticon.fromCodePoint(0x1f411),
            Emoticon.fromCodePoint(0x1f40e),
            Emoticon.fromCodePoint(0x1f416),
            Emoticon.fromCodePoint(0x1f400),
            Emoticon.fromCodePoint(0x1f401),
            Emoticon.fromCodePoint(0x1f413),
            Emoticon.fromCodePoint(0x1f983),
            Emoticon.fromCodePoint(0x1f54a),
            Emoticon.fromCodePoint(0x1f415),
            Emoticon.fromCodePoint(0x1f429),
            Emoticon.fromCodePoint(0x1f408),
            Emoticon.fromCodePoint(0x1f407),
            Emoticon.fromCodePoint(0x1f43f),
            Emoticon.fromCodePoint(0x1f43e),
            Emoticon.fromCodePoint(0x1f409),
            Emoticon.fromCodePoint(0x1f432),
            Emoticon.fromCodePoint(0x1f335),
            Emoticon.fromChar((char) 0xe033),
            Emoticon.fromCodePoint(0x1f332),
            Emoticon.fromCodePoint(0x1f333),
            Emoticon.fromCodePoint(0x1f334),
            Emoticon.fromChar((char) 0xe110),
            Emoticon.fromCodePoint(0x1f33f),
            Emoticon.fromCodePoint(0x1f340),
            Emoticon.fromCodePoint(0x1f38d),
            Emoticon.fromCodePoint(0x1f38b),
            Emoticon.fromCodePoint(0x1f343),
            Emoticon.fromCodePoint(0x1f342),
            Emoticon.fromCodePoint(0x1f341),
            Emoticon.fromCodePoint(0x1f33e),
            Emoticon.fromCodePoint(0x1f33a),
            Emoticon.fromCodePoint(0x1f33b),
            Emoticon.fromCodePoint(0x1f339),
            Emoticon.fromCodePoint(0x1f337),
            Emoticon.fromCodePoint(0x1f33c),
            Emoticon.fromCodePoint(0x1f338),
            Emoticon.fromCodePoint(0x1f490),
            Emoticon.fromCodePoint(0x1f344),
            Emoticon.fromCodePoint(0x1f330),
            Emoticon.fromCodePoint(0x1f383),
            Emoticon.fromCodePoint(0x1f41a),
            Emoticon.fromCodePoint(0x1f578),
            Emoticon.fromCodePoint(0x1f30d),
            Emoticon.fromCodePoint(0x1f30e),
            Emoticon.fromCodePoint(0x1f30f),
            Emoticon.fromCodePoint(0x1f315),
            Emoticon.fromCodePoint(0x1f316),
            Emoticon.fromCodePoint(0x1f317),
            Emoticon.fromCodePoint(0x1f318),
            Emoticon.fromCodePoint(0x1f311),
            Emoticon.fromCodePoint(0x1f312),
            Emoticon.fromCodePoint(0x1f313),
            Emoticon.fromCodePoint(0x1f314),
            Emoticon.fromCodePoint(0x1f31a),
            Emoticon.fromCodePoint(0x1f31d),
            Emoticon.fromCodePoint(0x1f31b),
            Emoticon.fromCodePoint(0x1f31c),
            Emoticon.fromCodePoint(0x1f31e),
            Emoticon.fromCodePoint(0x1f319),
            Emoticon.fromChar((char) 0x2b50),
            Emoticon.fromChar((char) 0xe335),
            Emoticon.fromChar((char) 0xe32e),
            Emoticon.fromChar((char) 0x2604),
            Emoticon.fromChar((char) 0x2600),
            Emoticon.fromCodePoint(0x1f324),
            Emoticon.fromChar((char) 0x26c5),
            Emoticon.fromCodePoint(0x1f325),
            Emoticon.fromCodePoint(0x1f326),
            Emoticon.fromChar((char) 0x2601),
            Emoticon.fromCodePoint(0x1f327),
            Emoticon.fromChar((char) 0x26c8),
            Emoticon.fromCodePoint(0x1f329),
            Emoticon.fromChar((char) 0x26a1),
            Emoticon.fromChar((char) 0xe11d),
            Emoticon.fromCodePoint(0x1f4a5),
            Emoticon.fromChar((char) 0x2744),
            Emoticon.fromCodePoint(0x1f328),
            Emoticon.fromChar((char) 0x2603),
            Emoticon.fromChar((char) 0x26c4),
            Emoticon.fromCodePoint(0x1f32c),
            Emoticon.fromCodePoint(0x1f4a8),
            Emoticon.fromCodePoint(0x1f32a),
            Emoticon.fromCodePoint(0x1f32b),
            Emoticon.fromChar((char) 0x2602),
            Emoticon.fromChar((char) 0x2614),
            Emoticon.fromCodePoint(0x1f4a6),
            Emoticon.fromCodePoint(0x1f4a7),
            Emoticon.fromCodePoint(0x1f30a),
    };
}
