/*
 * Copyright 2016 Hani Al Momani
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */


package com.kevalpatel2106.emoji_keyboard.internal.emoji;

/**
 * @author Hani Al Momani (hani.momanii@gmail.com)
 */
public class Electr {
    public static final Emojicon[] DATA = new Emojicon[]{
            Emojicon.fromChar((char) 0x231a),
            Emojicon.fromCodePoint(0x1f4f1),
            Emojicon.fromCodePoint(0x1f4f2),
            Emojicon.fromCodePoint(0x1f4bb),
            Emojicon.fromChar((char) 0x2328),
            Emojicon.fromCodePoint(0x1f5a5),
            Emojicon.fromCodePoint(0x1f5a8),
            Emojicon.fromCodePoint(0x1f5b1),
            Emojicon.fromCodePoint(0x1f5b2),
            Emojicon.fromCodePoint(0x1f579),
            Emojicon.fromCodePoint(0x1f5dc),
            Emojicon.fromCodePoint(0x1f4bd),
            Emojicon.fromCodePoint(0x1f4be),
            Emojicon.fromCodePoint(0x1f4bf),
            Emojicon.fromCodePoint(0x1f4c0),
            Emojicon.fromCodePoint(0x1f4fc),
            Emojicon.fromCodePoint(0x1f4f7),
            Emojicon.fromCodePoint(0x1f4f8),
            Emojicon.fromCodePoint(0x1f4f9),
            Emojicon.fromCodePoint(0x1f3a5),
            Emojicon.fromCodePoint(0x1f4fd),
            Emojicon.fromCodePoint(0x1f39e),
            Emojicon.fromCodePoint(0x1f4de),
            Emojicon.fromChar((char) 0x260e),
            Emojicon.fromCodePoint(0x1f4df),
            Emojicon.fromCodePoint(0x1f4e0),
            Emojicon.fromCodePoint(0x1f4fa),
            Emojicon.fromCodePoint(0x1f4fb),
            Emojicon.fromCodePoint(0x1f399),
            Emojicon.fromCodePoint(0x1f39a),
            Emojicon.fromCodePoint(0x1f39b),
            Emojicon.fromChar((char) 0x23f1),
            Emojicon.fromChar((char) 0x23f2),
            Emojicon.fromChar((char) 0x23f0),
            Emojicon.fromCodePoint(0x1f570),
            Emojicon.fromChar((char) 0x23f3),
            Emojicon.fromChar((char) 0x231b),
            Emojicon.fromCodePoint(0x1f4e1),
            Emojicon.fromCodePoint(0x1f50b),
            Emojicon.fromCodePoint(0x1f50c),
            Emojicon.fromCodePoint(0x1f4a1),
            Emojicon.fromCodePoint(0x1f526),
            Emojicon.fromCodePoint(0x1f56f),
            Emojicon.fromCodePoint(0x1f5d1),
            Emojicon.fromCodePoint(0x1f6e2),
            Emojicon.fromCodePoint(0x1f4b8),
            Emojicon.fromCodePoint(0x1f4b5),
            Emojicon.fromCodePoint(0x1f4b4),
            Emojicon.fromCodePoint(0x1f4b7),
            Emojicon.fromCodePoint(0x1f4b6),
            Emojicon.fromCodePoint(0x1f4b0),
            Emojicon.fromCodePoint(0x1f4b3),
            Emojicon.fromCodePoint(0x1f48e),
            Emojicon.fromChar((char) 0x2696),
            Emojicon.fromCodePoint(0x1f527),
            Emojicon.fromCodePoint(0x1f528),
            Emojicon.fromChar((char) 0x2692),
            Emojicon.fromCodePoint(0x1f6e0),
            Emojicon.fromChar((char) 0x26cf),
            Emojicon.fromCodePoint(0x1f529),
            Emojicon.fromChar((char) 0x2699),
            Emojicon.fromChar((char) 0x26d3),
            Emojicon.fromCodePoint(0x1f52b),
            Emojicon.fromCodePoint(0x1f4a3),
            Emojicon.fromCodePoint(0x1f52a),
            Emojicon.fromCodePoint(0x1f5e1),
            Emojicon.fromChar((char) 0x2694),
            Emojicon.fromCodePoint(0x1f6e1),
            Emojicon.fromCodePoint(0x1f6ac),
            Emojicon.fromChar((char) 0x2620),
            Emojicon.fromChar((char) 0x26b0),
            Emojicon.fromChar((char) 0x26b1),
            Emojicon.fromCodePoint(0x1f3fa),
            Emojicon.fromCodePoint(0x1f52e),
            Emojicon.fromCodePoint(0x1f4ff),
            Emojicon.fromCodePoint(0x1f488),
            Emojicon.fromChar((char) 0x2697),
            Emojicon.fromCodePoint(0x1f52c),
            Emojicon.fromCodePoint(0x1f52d),
            Emojicon.fromCodePoint(0x1f573),
            Emojicon.fromCodePoint(0x1f48a),
            Emojicon.fromCodePoint(0x1f489),
            Emojicon.fromCodePoint(0x1f321),
            Emojicon.fromCodePoint(0x1f3f7),
            Emojicon.fromCodePoint(0x1f516),
            Emojicon.fromCodePoint(0x1f6bd),
            Emojicon.fromCodePoint(0x1f6bf),
            Emojicon.fromCodePoint(0x1f6c1),
            Emojicon.fromCodePoint(0x1f511),
            Emojicon.fromCodePoint(0x1f5dd),
            Emojicon.fromCodePoint(0x1f6cb),
            Emojicon.fromCodePoint(0x1f6cc),
            Emojicon.fromCodePoint(0x1f6cf),
            Emojicon.fromCodePoint(0x1f6aa),
            Emojicon.fromCodePoint(0x1f6ce),
            Emojicon.fromCodePoint(0x1f5bc),
            Emojicon.fromCodePoint(0x1f5fa),
            Emojicon.fromChar((char) 0x26f1),
            Emojicon.fromCodePoint(0x1f5ff),
            Emojicon.fromCodePoint(0x1f6cd),
            Emojicon.fromCodePoint(0x1f388),
            Emojicon.fromCodePoint(0x1f38f),
            Emojicon.fromCodePoint(0x1f380),
            Emojicon.fromCodePoint(0x1f381),
            Emojicon.fromCodePoint(0x1f38a),
            Emojicon.fromCodePoint(0x1f389),
            Emojicon.fromChar((char) 0xe438),
            Emojicon.fromCodePoint(0x1f390),
            Emojicon.fromCodePoint(0x1f38c),
            Emojicon.fromCodePoint(0x1f3ee),
            Emojicon.fromChar((char) 0x2709),
            Emojicon.fromCodePoint(0x1f4e9),
            Emojicon.fromCodePoint(0x1f4e8),
            Emojicon.fromCodePoint(0x1f4e7),
            Emojicon.fromCodePoint(0x1f48c),
            Emojicon.fromCodePoint(0x1f4ee),
            Emojicon.fromCodePoint(0x1f4ea),
            Emojicon.fromCodePoint(0x1f4eb),
            Emojicon.fromCodePoint(0x1f4ec),
            Emojicon.fromCodePoint(0x1f4ed),
            Emojicon.fromCodePoint(0x1f4e6),
            Emojicon.fromCodePoint(0x1f4ef),
            Emojicon.fromCodePoint(0x1f4e5),
            Emojicon.fromCodePoint(0x1f4e4),
            Emojicon.fromCodePoint(0x1f4dc),
            Emojicon.fromCodePoint(0x1f4c3),
            Emojicon.fromCodePoint(0x1f4d1),
            Emojicon.fromCodePoint(0x1f4ca),
            Emojicon.fromCodePoint(0x1f4c8),
            Emojicon.fromCodePoint(0x1f4c9),
            Emojicon.fromCodePoint(0x1f4c4),
            Emojicon.fromCodePoint(0x1f4c5),
            Emojicon.fromCodePoint(0x1f4c6),
            Emojicon.fromCodePoint(0x1f5d3),
            Emojicon.fromCodePoint(0x1f4c7),
            Emojicon.fromCodePoint(0x1f5c3),
            Emojicon.fromCodePoint(0x1f5f3),
            Emojicon.fromCodePoint(0x1f5c4),
            Emojicon.fromCodePoint(0x1f4cb),
            Emojicon.fromCodePoint(0x1f5d2),
            Emojicon.fromCodePoint(0x1f4c1),
            Emojicon.fromCodePoint(0x1f4c2),
            Emojicon.fromCodePoint(0x1f5c2),
            Emojicon.fromCodePoint(0x1f5de),
            Emojicon.fromCodePoint(0x1f4f0),
            Emojicon.fromCodePoint(0x1f4d3),
            Emojicon.fromCodePoint(0x1f4d5),
            Emojicon.fromCodePoint(0x1f4d7),
            Emojicon.fromCodePoint(0x1f4d8),
            Emojicon.fromCodePoint(0x1f4d9),
            Emojicon.fromCodePoint(0x1f4d4),
            Emojicon.fromCodePoint(0x1f4d2),
            Emojicon.fromCodePoint(0x1f4da),
            Emojicon.fromCodePoint(0x1f4d6),
            Emojicon.fromCodePoint(0x1f517),
            Emojicon.fromCodePoint(0x1f4ce),
            Emojicon.fromCodePoint(0x1f587),
            Emojicon.fromChar((char) 0x2702),
            Emojicon.fromCodePoint(0x1f4d0),
            Emojicon.fromCodePoint(0x1f4cf),
            Emojicon.fromCodePoint(0x1f4cc),
            Emojicon.fromCodePoint(0x1f4cd),
            Emojicon.fromCodePoint(0x1f3f3),
            Emojicon.fromCodePoint(0x1f3f4),
            Emojicon.fromCodePoint(0x1f510),
            Emojicon.fromCodePoint(0x1f512),
            Emojicon.fromCodePoint(0x1f513),
            Emojicon.fromCodePoint(0x1f50f),
            Emojicon.fromCodePoint(0x1f58a),
            Emojicon.fromCodePoint(0x1f58b),
            Emojicon.fromChar((char) 0x2712),
            Emojicon.fromCodePoint(0x1f4dd),
            Emojicon.fromChar((char) 0x270f),
            Emojicon.fromCodePoint(0x1f58d),
            Emojicon.fromCodePoint(0x1f58c),
            Emojicon.fromCodePoint(0x1f50d),
            Emojicon.fromCodePoint(0x1f50e),
    };
}
